### ISSUE TITLE
Incremental slides locks the next navigation

### ISSUE THREAD

**Issue by tobiassjosten** [Seldaek/slippy#14]
In the example, once you start incrementing [the last slide](http://slides.seld.be/?file=2010-05-30+Example.html#6) and then go back (left), every attempt to go right will not move you forward but instead increment the last slide. When it's full, hitting right will again take you forward.

Reproduce:

- Visit [page 5 in the example](http://slides.seld.be/?file=2010-05-30+Example.html#5).
- Hit right and right again, to trigger incrementation.
- Hit left to go back to page 5.
- Hit right. Instead of going to page 6, this keeps incrementing the last page and keeps you at page 5.

**Comment by SoboLAN** [comment]
Hmmm, sounds like a bit of a challenge. I'll give it a shot, sometime this month :) .

**Comment by Seldaek** [comment]
Oh I actually fixed this now.. shift+right-arrow goes over to the next slide and marks all incremental stuff as "visible".
