### ISSUE TITLE
Incremental presentations

### ISSUE THREAD

**Issue by FrankWSamuelson** [Seldaek/slippy#19]
Is there a way to make incremental presentations that are out of order?  For example by specifying a increment number or something?   In reveal.js I can do this:
```
<li class="fragment" data-fragment-index="3" >third</li>
<li class="fragment" data-fragment-index="2" >second</li>
<li class="fragment" data-fragment-index="1" >first</li>
```

which makes list items appear from the bottom first.
Thanks for any help.

**Comment by Seldaek** [comment]
Nope, no way to do this. Would be possible to add it, but I don't have the need for it so feel free to PR if you need it.
